### PR TITLE
Add some badges

### LINKED ISSUE #21: [Docs] Add badges in README
Every repo seems to have badges. I really don't understand how they work

Can someone help?

/cc @Aaron-Junker

### PR DESCRIPTION
**Pull request by alannt777**
Resolves #21

I added some badges but I am looking to add more

### CODE REVIEW

**Comment by alannt777** [comment]
I am merging this

**Comment by Aaron-Junker** [comment]
Looks good

**Comment by alannt777** [comment]
Awesome!

**Pull request merged**
